-- Vista DatosConsultas
USE BETANIA
GO
--IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('DatosConsultas'))
--BEGIN
--	DROP VIEW DatosConsultas
--END
--GO
--CREATE VIEW dbo.DatosConsultas
--AS
SELECT
	DISTINCT
	 CONVERT(BIGINT,TIMOVIMIENTOENCAB.MV_COD, 0) Codigo
	,CONVERT(DATE, CONVERT(VARCHAR, CAST(dbo.TKCLIENTES.KC_FCH_NACE AS INT))) AS FechaNacimiento
	,dbo.FUX_CALCULAR_EDAD(dbo.TKCLIENTES.KC_FCH_NACE,CONVERT(VARCHAR(8),MV_FCH,112),'N') Edad
	,dbo.FUX_CALCULAR_EDAD(dbo.TKCLIENTES.KC_FCH_NACE, CONVERT(VARCHAR(8), dbo.TIMOVIMIENTOENCAB.MV_FCH, 112), 'U') UnidadEdad
	,ISNULL(dbo.TMUSUARIOSFACTURACION.KC2_SEXO, '') Sexo
	,ISNULL(dbo.TMUSUARIOSFACTURACION.KC2_ZONA_U, 0) Zona
	,CASE TMUSUARIOSFACTURACION.KC2_ES_EXTRANJERO
		WHEN 'S' THEN 'S'
		WHEN NULL THEN 'N'
		ELSE 'N'
	END EsExtranjero
	,'ANTIOQUIA' Departamento
	,'BETANIA' Municipio
	,CONVERT(DATE, CONVERT(VARCHAR, CAST(dbo.TIMOVIMIENTOENCAB.MV_FCH AS INT))) AS FechaAtencion
	,YEAR(CONVERT(VARCHAR,CAST(CAST(TIMOVIMIENTOENCAB.MV_FCH AS VARCHAR) AS DATE),111)) AñoAtencion
	,Month(CONVERT(VARCHAR,CAST(CAST(TIMOVIMIENTOENCAB.MV_FCH AS VARCHAR) AS DATE),111)) MesAtencion
	,DATENAME(MONTH,CONVERT(VARCHAR,CAST(CAST(TIMOVIMIENTOENCAB.MV_FCH AS VARCHAR) AS DATE),111)) NombreMes
	,TMENTIDADES.ENT_COD_SUPER AS CodigoSupersalud
	,ISNULL(dbo.TMENTIDADES.ENT_NOMBRE, '') NombreEntidad
	,(CASE TMENTIDADES.ENT_TIPO
		WHEN '1' THEN 'CONTRIBUTIVO' 
		WHEN '2' THEN 'SUBSIDIADO' 
		WHEN '3' THEN 'VINCULADO' 
		WHEN '4' THEN 'PARTICULAR'
		WHEN '5' THEN 'OTRO' 
		WHEN '6' THEN 'ARP' 
		WHEN '7' THEN 'P.COMP.EPS' 
		WHEN '8' THEN 'P.COMP.EMP' 
		WHEN '9' THEN 'ASEGURADORAS'
		WHEN 'A' THEN 'ACCID.TRANSITO' 
		WHEN 'B' THEN 'E.S.E.' 
		WHEN 'C' THEN 'PREV.SOCIAL' END)
	Regimen
	,SUBSTRING(TIMOVIMIENTODETALLE.MV2_ARTIC,2,6) CodigoCups
	,CASE TIMOVIMIENTODETALLE.MV2_ARTIC
		WHEN '*890201' THEN 'CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL'
		WHEN '*890300' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR MEDICINA GENERAL'
		WHEN '*890301' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR MEDICINA GENERAL'
		WHEN '*890701' THEN 'CONSULTA DE URGENCIAS POR MEDICINA GENERAL'
		WHEN '*890201-1' THEN 'CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL'
		WHEN '*890301-1' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR MEDICINA GENERAL'
		WHEN '*890301-3' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR MEDICINA GENERAL'
		WHEN '*890201-4' THEN 'CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL'
		WHEN '*890201-5' THEN 'CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL'
		WHEN '*890205-5' THEN 'CONSULTA DE PRIMERA VEZ POR ENFERMERIA'
		WHEN '*890301-5' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR MEDICINA GENERAL'
		WHEN '*890305-5' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR ENFERMERIA'
		WHEN '*890201-6' THEN 'CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL'
		WHEN '*890301-6' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR MEDICINA GENERAL'
		WHEN '*890305-6' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR ENFERMERIA'
		WHEN '*890201-7' THEN 'CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL'
		WHEN '*890305-7' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR ENFERMERIA'
		WHEN '*890201-8' THEN 'CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL'
		WHEN '*890203-8' THEN 'CONSULTA DE PRIMERA VEZ POR ODONTOLOGIA GENERAL'
		WHEN '*890205-8' THEN 'CONSULTA DE PRIMERA VEZ POR ENFERMERIA'
		WHEN '*890301-8' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR MEDICINA GENERAL'
		WHEN '*890305-8' THEN 'CONSULTA DE CONTROL O DE SEGUIMIENTO POR ENFERMERIA'
		WHEN '*890201-9' THEN 'CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL'
	 END AS DescripcionCups
	,CASE TIMOVIMIENTODETALLE.MV2_ARTIC
		WHEN '*890201' THEN 'CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL'
		WHEN '*890300' THEN 'CONSULTA DE SEGUIMIENTO REVISION'
		WHEN '*890301' THEN 'CONSULTA DE CONTROL MEDICO HTA PARA EPS'
		WHEN '*890701' THEN 'CONSULTA DE URGENCIAS POR MEDICINA GENERAL'
		WHEN '*890201-1' THEN 'CONSULTA DE PRIMERA VEZ HTA- MEDICO'
		WHEN '*890301-1' THEN 'CONSULTA DE CONTROL MEDICO DE HTA'
		WHEN '*890301-3' THEN 'PYP CONSULTA DE CONTROL POR MEDICO POSTPARTO'
		WHEN '*890201-4' THEN 'PYP CONSULTA DE CONTROL POR MEDICO RECIEN NACIDO'
		WHEN '*890201-5' THEN 'PYP CONSULTA PRIMERA VEZ PLANIFICACION FAMILIAR MEDICO'
		WHEN '*890205-5' THEN 'PYP CONSULTA PRIMERA VEZ PLANIFICACION FAMILIAR ENFERMERA'
		WHEN '*890301-5' THEN 'PYP CONSULTA CONTROL PLANIFICACION FAMLIAR MEDICO'
		WHEN '*890305-5' THEN 'PYP CONSULTA CONTROL PLANIFICACION FAMILIAR ENFERMERA'
		WHEN '*890201-6' THEN 'PYP CONSULTA PRIMERA VEZ CYD MEDICO'
		WHEN '*890301-6' THEN 'PYP CONSULTA CONTROL CYD MEDICO'
		WHEN '*890305-6' THEN 'PYP CONSULTA CONTROL CYD ENFERMERA'
		WHEN '*890201-7' THEN 'PYP CONSULTA PRIMERA VEZ JOVEN MEDICO'
		WHEN '*890305-7' THEN 'CONSULTA DE CONTROL POR ENFERMERIA HTA'
		WHEN '*890201-8' THEN 'PYP CONSULTA PRIMERA VEZ PRENATAL MEDICO'
		WHEN '*890203-8' THEN 'PYP CONSULTA POR ODONTOLOGIA GENERAL - MATERNA'
		WHEN '*890205-8' THEN 'PYP CONSULTA DE PRIMERA VEZ CONTROL PRENATAL ENFERMERIA'
		WHEN '*890301-8' THEN 'PYP CONSULTA CONTROL PRENATAL MEDICO'
		WHEN '*890305-8' THEN 'PYP CONSULTA DE CONTROL ENFERMERIA GESTANTES'
		WHEN '*890201-9' THEN 'PYP CONSULTA PRIMERA VEZ ADULTO MEDICO'
	 END AS ConceptoProduccion
	
FROM dbo.TIMOVIMIENTOENCAB
LEFT JOIN TIMOVIMIENTODETALLE 
	ON (TIMOVIMIENTODETALLE.MV2_TIPO = TIMOVIMIENTOENCAB.MV_TIPO 
	AND TIMOVIMIENTODETALLE.MV2_NUM = TIMOVIMIENTOENCAB.MV_NUM)
LEFT JOIN dbo.TMMOVIMIENTOFACTURACIONE 
	ON dbo.TMMOVIMIENTOFACTURACIONE.MV1_TIPO = dbo.TIMOVIMIENTOENCAB.MV_TIPO AND
	dbo.TMMOVIMIENTOFACTURACIONE.MV1_NUM = dbo.TIMOVIMIENTOENCAB.MV_NUM 
LEFT JOIN dbo.TKCLIENTES
	ON dbo.TKCLIENTES.KC_ZONA = dbo.TIMOVIMIENTOENCAB.MV_ZONA AND 
	dbo.TKCLIENTES.KC_COD = dbo.TIMOVIMIENTOENCAB.MV_COD AND 
	dbo.TKCLIENTES.KC_SEQK = dbo.TIMOVIMIENTOENCAB.MV_SEQK 
LEFT JOIN dbo.TMUSUARIOSFACTURACION
	ON dbo.TMUSUARIOSFACTURACION.KC2_ZONA = dbo.TIMOVIMIENTOENCAB.MV_ZONA AND 
	dbo.TMUSUARIOSFACTURACION.KC2_COD = dbo.TIMOVIMIENTOENCAB.MV_COD AND 
	dbo.TMUSUARIOSFACTURACION.KC2_SEQK = dbo.TIMOVIMIENTOENCAB.MV_SEQK 
LEFT JOIN dbo.TMENTIDADES ON dbo.TMMOVIMIENTOFACTURACIONE.MV1_ENTIDAD = dbo.TMENTIDADES.ENT_COD 
LEFT JOIN TITIPOSDOCUMENTOS ON (TITIPOSDOCUMENTOS.TA_TIPO_DOC = TIMOVIMIENTOENCAB.MV_TIPO)
LEFT JOIN dbo.TIARTICULOS ON dbo.TIARTICULOS.MI_ARTIC = dbo.TIMOVIMIENTODETALLE.MV2_ARTIC 
WHERE TIMOVIMIENTOENCAB.MV_ANULADO IS NULL
AND TIMOVIMIENTOENCAB.MV_TIPO IN ('V01','V02','V03','V04','V05','V06','V07','V08','V09','V10','V11','V12','V13','V14','V20','V21','V22','V23','V24','V25','V26','V27') --131.029
AND TIMOVIMIENTODETALLE.MV2_ARTIC IN 
	(
		 '*890201'
		,'*890300'
		,'*890301'
		,'*890701'
		,'*890201-1'
		,'*890301-1'
		,'*890301-3'
		,'*890201-4'
		,'*890201-5'
		,'*890205-5'
		,'*890301-5'
		,'*890305-5'
		,'*890201-6'
		,'*890301-6'
		,'*890305-6'
		,'*890201-7'
		,'*890305-7'
		,'*890201-8'
		,'*890203-8'
		,'*890205-8'
		,'*890301-8'
		,'*890305-8'
		,'*890201-9'
	)
AND TIMOVIMIENTOENCAB.MV_FCH > 20121231
AND TKCLIENTES.KC_FCH_NACE IS NOT NULL
AND TMENTIDADES.ENT_COD_SUPER IS NOT NULL
AND dbo.TIMOVIMIENTOENCAB.MV_ZONA = '99'
--ORDER BY FechaAtencion DESC