-- Higiene Oral
SELECT
	 DISTINCT
	 CONVERT(BIGINT,TIMOVIMIENTOENCAB.MV_COD, 0) Codigo
	,CONVERT(DATE, CONVERT(VARCHAR, CAST(dbo.TKCLIENTES.KC_FCH_NACE AS INT))) AS FechaNacimiento
	,dbo.FUX_CALCULAR_EDAD(dbo.TKCLIENTES.KC_FCH_NACE,CONVERT(VARCHAR(8),MV_FCH,112),'N') Edad
	,dbo.FUX_CALCULAR_EDAD(dbo.TKCLIENTES.KC_FCH_NACE, CONVERT(VARCHAR(8), dbo.TIMOVIMIENTOENCAB.MV_FCH, 112), 'U') UnidadEdad
	,ISNULL(dbo.TMUSUARIOSFACTURACION.KC2_SEXO, '') Sexo
	,ISNULL(dbo.TMUSUARIOSFACTURACION.KC2_ZONA_U, 0) Zona
	,CASE TMUSUARIOSFACTURACION.KC2_ES_EXTRANJERO
		WHEN 'S' THEN 'S'
		WHEN NULL THEN 'N'
		ELSE 'N'
	 END EsExtranjero
	,'ANTIOQUIA' Departamento
	,'BETANIA' Municipio
	,CONVERT(DATE, CONVERT(VARCHAR, CAST(dbo.TIMOVIMIENTOENCAB.MV_FCH AS INT))) AS FechaAtencion
	,YEAR(CONVERT(VARCHAR,CAST(CAST(TIMOVIMIENTOENCAB.MV_FCH AS VARCHAR) AS DATE),111)) AñoAtencion
	,Month(CONVERT(VARCHAR,CAST(CAST(TIMOVIMIENTOENCAB.MV_FCH AS VARCHAR) AS DATE),111)) MesAtencion
	,DATENAME(MONTH,CONVERT(VARCHAR,CAST(CAST(TIMOVIMIENTOENCAB.MV_FCH AS VARCHAR) AS DATE),111)) NombreMes
	,TMENTIDADES.ENT_COD_SUPER AS CodigoSupersalud
	,ISNULL(dbo.TMENTIDADES.ENT_NOMBRE, '') NombreEntidad
	,(CASE TMENTIDADES.ENT_TIPO
		WHEN '1' THEN 'CONTRIBUTIVO' 
		WHEN '2' THEN 'SUBSIDIADO' 
		WHEN '3' THEN 'VINCULADO' 
		WHEN '4' THEN 'PARTICULAR'
		WHEN '5' THEN 'OTRO' 
		WHEN '6' THEN 'ARP' 
		WHEN '7' THEN 'P.COMP.EPS' 
		WHEN '8' THEN 'P.COMP.EMP' 
		WHEN '9' THEN 'ASEGURADORAS'
		WHEN 'A' THEN 'ACCID.TRANSITO' 
		WHEN 'B' THEN 'E.S.E.' 
		WHEN 'C' THEN 'PREV.SOCIAL' END)
	 Regimen
	,SUBSTRING(TIMOVIMIENTODETALLE.MV2_ARTIC,2,6) CodigoCups
	,CASE TIMOVIMIENTODETALLE.MV2_ARTIC
		WHEN '*997102-2' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S1' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S2' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S3' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S4' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S5' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S6' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S7' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S8' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997103-2' THEN 'TOPICACION DE FLUOR EN GEL'
		WHEN '*997103-15' THEN 'TOPICACION DE FLUOR EN GEL'
		WHEN '*997310-2' THEN 'CONTROL DE PLACA DENTAL NCOC'
		WHEN '*997300-2' THEN 'DETARTRAJE SUPRAGINGIVAL SOD'
		WHEN '*997106-2' THEN 'TOPICACION DE FLUOR EN BARNIZ'
		WHEN '*C00015-2' THEN 'TOPICACION DE FLUOR EN BARNIZ'
		WHEN '*997100-2' THEN 'TOPICACION DE FLUOR EN BARNIZ'
		WHEN '*997106' THEN 'TOPICACION DE FLUOR EN BARNIZ'
		WHEN '*C00015' THEN 'TOPICACION DE FLUOR EN BARNIZ'
	 END AS DescripcionCups
	,CASE TIMOVIMIENTODETALLE.MV2_ARTIC
		WHEN '*997102-2' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S1' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S2' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S3' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S4' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S5' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S6' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S7' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997102-2-S8' THEN 'APLICACION DE SELLANTES DE FOTOCURADO'
		WHEN '*997103-2' THEN 'TOPICACION DE FLUOR EN GEL'
		WHEN '*997103-15' THEN 'TOPICACION DE FLUOR EN GEL'
		WHEN '*997310-2' THEN 'CONTROL DE PLACA DENTAL NCOC'
		WHEN '*997300-2' THEN 'DETARTRAJE SUPRAGINGIVAL SOD'
		WHEN '*997106-2' THEN 'TOPICACION DE FLUOR EN BARNIZ'
		WHEN '*C00015-2' THEN 'TOPICACION DE FLUOR EN BARNIZ'
		WHEN '*997100-2' THEN 'TOPICACION DE FLUOR EN BARNIZ'
		WHEN '*997106' THEN 'TOPICACION DE FLUOR EN BARNIZ'
		WHEN '*C00015' THEN 'TOPICACION DE FLUOR EN BARNIZ'
	  END AS ConceptoProduccion
	,CASE
		WHEN TIMOVIMIENTODETALLE.MV2_ARTIC = '*997102-2-S1' THEN (CONVERT(INT,dbo.TIMOVIMIENTODETALLE.MV2_CANT1, 0) * 1)
		WHEN TIMOVIMIENTODETALLE.MV2_ARTIC = '*997102-2-S2' THEN (CONVERT(INT,dbo.TIMOVIMIENTODETALLE.MV2_CANT1, 0) * 2)
		WHEN TIMOVIMIENTODETALLE.MV2_ARTIC = '*997102-2-S3' THEN (CONVERT(INT,dbo.TIMOVIMIENTODETALLE.MV2_CANT1, 0) * 3)
		WHEN TIMOVIMIENTODETALLE.MV2_ARTIC = '*997102-2-S4' THEN (CONVERT(INT,dbo.TIMOVIMIENTODETALLE.MV2_CANT1, 0) * 4)
		WHEN TIMOVIMIENTODETALLE.MV2_ARTIC = '*997102-2-S5' THEN (CONVERT(INT,dbo.TIMOVIMIENTODETALLE.MV2_CANT1, 0) * 5)
		WHEN TIMOVIMIENTODETALLE.MV2_ARTIC = '*997102-2-S6' THEN (CONVERT(INT,dbo.TIMOVIMIENTODETALLE.MV2_CANT1, 0) * 6)
		WHEN TIMOVIMIENTODETALLE.MV2_ARTIC = '*997102-2-S7' THEN (CONVERT(INT,dbo.TIMOVIMIENTODETALLE.MV2_CANT1, 0) * 7)
		WHEN TIMOVIMIENTODETALLE.MV2_ARTIC = '*997102-2-S8' THEN (CONVERT(INT,dbo.TIMOVIMIENTODETALLE.MV2_CANT1, 0) * 8)
		ELSE CONVERT(INT,dbo.TIMOVIMIENTODETALLE.MV2_CANT1, 0)
	END AS Cantidad

FROM dbo.TIMOVIMIENTOENCAB
	LEFT JOIN TIMOVIMIENTODETALLE 
		ON (TIMOVIMIENTODETALLE.MV2_TIPO = TIMOVIMIENTOENCAB.MV_TIPO 
		AND TIMOVIMIENTODETALLE.MV2_NUM = TIMOVIMIENTOENCAB.MV_NUM)
	LEFT JOIN dbo.TMMOVIMIENTOFACTURACIONE 
		ON dbo.TMMOVIMIENTOFACTURACIONE.MV1_TIPO = dbo.TIMOVIMIENTOENCAB.MV_TIPO AND
		dbo.TMMOVIMIENTOFACTURACIONE.MV1_NUM = dbo.TIMOVIMIENTOENCAB.MV_NUM 
	LEFT JOIN dbo.TKCLIENTES
		ON dbo.TKCLIENTES.KC_ZONA = dbo.TIMOVIMIENTOENCAB.MV_ZONA AND 
		dbo.TKCLIENTES.KC_COD = dbo.TIMOVIMIENTOENCAB.MV_COD AND 
		dbo.TKCLIENTES.KC_SEQK = dbo.TIMOVIMIENTOENCAB.MV_SEQK 
	LEFT JOIN dbo.TMUSUARIOSFACTURACION
		ON dbo.TMUSUARIOSFACTURACION.KC2_ZONA = dbo.TIMOVIMIENTOENCAB.MV_ZONA AND 
		dbo.TMUSUARIOSFACTURACION.KC2_COD = dbo.TIMOVIMIENTOENCAB.MV_COD AND 
		dbo.TMUSUARIOSFACTURACION.KC2_SEQK = dbo.TIMOVIMIENTOENCAB.MV_SEQK 
	LEFT JOIN dbo.TMENTIDADES ON dbo.TMMOVIMIENTOFACTURACIONE.MV1_ENTIDAD = dbo.TMENTIDADES.ENT_COD 
	LEFT JOIN TITIPOSDOCUMENTOS ON (TITIPOSDOCUMENTOS.TA_TIPO_DOC = TIMOVIMIENTOENCAB.MV_TIPO)
	LEFT JOIN dbo.TIARTICULOS ON dbo.TIARTICULOS.MI_ARTIC = dbo.TIMOVIMIENTODETALLE.MV2_ARTIC 
	WHERE TIMOVIMIENTOENCAB.MV_ANULADO IS NULL
	AND TIMOVIMIENTOENCAB.MV_TIPO IN ('V01','V02','V03','V04','V05','V06','V07','V08','V09','V10','V11','V12','V13','V14','V20','V21','V22','V23','V24','V25','V26','V27')
	AND TIMOVIMIENTODETALLE.MV2_ARTIC IN
		(
		 '*997102-2'
		,'*997102-2-S1'
		,'*997102-2-S2'
		,'*997102-2-S3'
		,'*997102-2-S4'
		,'*997102-2-S5'
		,'*997102-2-S6'
		,'*997102-2-S7'
		,'*997102-2-S8'
		,'*997103-2'
		,'*997103-15'
		,'*997310-2'
		,'*997300-2'
		,'*997106-2'
		,'*C00015-2'
		,'*997100-2'
		,'*997106'
		,'*C00015'
		)
	AND TIMOVIMIENTOENCAB.MV_FCH > 20121231
	AND TKCLIENTES.KC_FCH_NACE IS NOT NULL
	AND TMENTIDADES.ENT_COD_SUPER IS NOT NULL
	AND dbo.TIMOVIMIENTOENCAB.MV_ZONA = '99'
