-- PYP
USE
BETANIA
GO
SELECT
	 DISTINCT
	 CONVERT(BIGINT,TIMOVIMIENTOENCAB.MV_COD, 0) Codigo
	,CONVERT(DATE, CONVERT(VARCHAR, CAST(dbo.TKCLIENTES.KC_FCH_NACE AS INT))) AS FechaNacimiento
	,dbo.FUX_CALCULAR_EDAD(dbo.TKCLIENTES.KC_FCH_NACE,CONVERT(VARCHAR(8),MV_FCH,112),'N') Edad
	,dbo.FUX_CALCULAR_EDAD(dbo.TKCLIENTES.KC_FCH_NACE, CONVERT(VARCHAR(8), dbo.TIMOVIMIENTOENCAB.MV_FCH, 112), 'U') UnidadEdad
	,ISNULL(dbo.TMUSUARIOSFACTURACION.KC2_SEXO, '') Sexo
	,ISNULL(dbo.TMUSUARIOSFACTURACION.KC2_ZONA_U, 0) Zona
	,CASE TMUSUARIOSFACTURACION.KC2_ES_EXTRANJERO
		WHEN 'S' THEN 'S'
		WHEN NULL THEN 'N'
		ELSE 'N'
	 END EsExtranjero
	,'ANTIOQUIA' Departamento
	,'BETANIA' Municipio
	,CONVERT(DATE, CONVERT(VARCHAR, CAST(dbo.TIMOVIMIENTOENCAB.MV_FCH AS INT))) AS FechaAtencion
	,YEAR(CONVERT(VARCHAR,CAST(CAST(TIMOVIMIENTOENCAB.MV_FCH AS VARCHAR) AS DATE),111)) AñoAtencion
	,Month(CONVERT(VARCHAR,CAST(CAST(TIMOVIMIENTOENCAB.MV_FCH AS VARCHAR) AS DATE),111)) MesAtencion
	,DATENAME(MONTH,CONVERT(VARCHAR,CAST(CAST(TIMOVIMIENTOENCAB.MV_FCH AS VARCHAR) AS DATE),111)) NombreMes
	,TMENTIDADES.ENT_COD_SUPER AS CodigoSupersalud
	,ISNULL(dbo.TMENTIDADES.ENT_NOMBRE, '') NombreEntidad
	,(CASE TMENTIDADES.ENT_TIPO
		WHEN '1' THEN 'CONTRIBUTIVO' 
		WHEN '2' THEN 'SUBSIDIADO' 
		WHEN '3' THEN 'VINCULADO' 
		WHEN '4' THEN 'PARTICULAR'
		WHEN '5' THEN 'OTRO' 
		WHEN '6' THEN 'ARP' 
		WHEN '7' THEN 'P.COMP.EPS' 
		WHEN '8' THEN 'P.COMP.EMP' 
		WHEN '9' THEN 'ASEGURADORAS'
		WHEN 'A' THEN 'ACCID.TRANSITO' 
		WHEN 'B' THEN 'E.S.E.' 
		WHEN 'C' THEN 'PREV.SOCIAL' END)
	 Regimen
	,SUBSTRING(TIMOVIMIENTODETALLE.MV2_ARTIC,2,6) CodigoCups
	,CASE TIMOVIMIENTODETALLE.MV2_ARTIC
		WHEN '*892901-10' THEN 'TOMA NO QUIRURGICA DE MUESTRA O TEJIDO VAGINAL PARA ESTUDIO CITOLOGICO (CCV)'
		WHEN '*950601-12' THEN 'MEDICION DE AGUDEZA VISUAL'
		WHEN '*993102'    THEN 'VACUNACION CONTRA TUBERCULOSIS (BCG)'
		WHEN '*993102-4'  THEN 'VACUNACION CONTRA TUBERCULOSIS (BCG)'
		WHEN '*993104-1'  THEN 'VACUNACION CONTRA HAEMOPHILUS INFLUENZA TIPO B'
		WHEN '*993106-1'  THEN 'VACUNACION CONTRA NEUMOCOCO'
		WHEN '*993120'    THEN 'VACUNACION COMBINADA CONTRA TETANOS Y DIFTERIA (TD)'
		WHEN '*993120-8'  THEN 'VACUNACION COMBINADA CONTRA TETANOS Y DIFTERIA (TD)'
		WHEN '*993122'    THEN 'VACUNACION COMBINADA CONTRA DIFTERIATETANOS Y TOS FERINA (DPT)'
		WHEN '*993130-1'  THEN 'VACUNACION COMBINADA CONTRA HAEMOPHILUS INFLUENZA TIPO B DIFTERIA TETANOS TOS FERINA Y HEPATITIS B (PENTAVALENTE)'
		WHEN '*993501'    THEN 'VACUNACION CONTRA POLIOMIELITIS (VOP O IVP)'
		WHEN '*993502-1'  THEN 'VACUNACION CONTRA HEPATITIS A'
		WHEN '*993503-1'  THEN 'VACUNACION CONTRA HEPATITIS B'
		WHEN '*993503-4'  THEN 'VACUNACION CONTRA HEPATITIS B'
		WHEN '*993504-1'  THEN 'VACUNACION CONTRA FIEBRE AMARILLA'
		WHEN '*993505'    THEN 'VACUNACION CONTRA RABIA'
		WHEN '*993506-1'  THEN 'VACUNACION CONTRA SARAMPION'
		WHEN '*993509-1'  THEN 'VACUNACION CONTRA VARICELA'
		WHEN '*993510-1'  THEN 'VACUNACION CONTRA INFLUENZA'
		WHEN '*993512-1'  THEN 'VACUNACION CONTRA ROTAVIRUS'
		WHEN '*993513'    THEN 'VACUNACION CONTRA VIRUS PAPILOMA HUMANO [VPH]'
		WHEN '*993520'    THEN 'VACUNACION COMBINADA CONTRA SARAMPION Y RUBEOLA (SR) (DOBLE VIRAL)'
		WHEN '*993522'    THEN 'VACUNACION COMBINADA CONTRA SARAMPION PAROTIDITIS Y RUBEOLA (SRP) (TRIPLE VIRAL)'
		WHEN '*993522-1'  THEN 'VACUNACION COMBINADA CONTRA SARAMPION PAROTIDITIS Y RUBEOLA (SRP) (TRIPLE VIRAL)'
		WHEN '*995201'    THEN 'OTRA VACUNACION DEL PROGRAMA AMPLIADO DE INMUNIZACIONES'
		WHEN '697100'     THEN 'INSERCION DE DISPOSITIVO INTRAUTERINO ANTICONCEPTIVO (DIU) SOD'
		WHEN '*861801'    THEN 'INSERCION DE ANTICONCEPTIVOS SUBDERMICOS'
	 END AS DescripcionCups
	,CASE TIMOVIMIENTODETALLE.MV2_ARTIC
		WHEN '*892901-10' THEN  'CITOLOGIAS CERVICOVAGINALES TOMADAS'
		WHEN '*950601-12' THEN  'PYP MEDICION DE LA AGUDEZA VISUAL'
		WHEN '*993102'    THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993102-4'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993104-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993106-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993120'    THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993120-8'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993122'    THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993130-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993501'    THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993502-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993503-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993503-4'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993504-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993505'    THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993506-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993509-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993510-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993512-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993513'    THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993520'    THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993522'    THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*993522-1'  THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*995201'    THEN  'DOSIS DE BIOLOGICO APLICADAS'
		WHEN '*697100'	  THEN  'INSERCION DE DISPOSITIVO INTRAUTERINO ANTICONCEPTIVO (DIU)'
		WHEN '*861801'    THEN  'INSERCION DE IMPLANTE SUBDERMICO'
	  END AS ConceptoProduccion

FROM dbo.TIMOVIMIENTOENCAB
	LEFT JOIN TIMOVIMIENTODETALLE 
		ON (TIMOVIMIENTODETALLE.MV2_TIPO = TIMOVIMIENTOENCAB.MV_TIPO 
		AND TIMOVIMIENTODETALLE.MV2_NUM = TIMOVIMIENTOENCAB.MV_NUM)
	LEFT JOIN dbo.TMMOVIMIENTOFACTURACIONE 
		ON dbo.TMMOVIMIENTOFACTURACIONE.MV1_TIPO = dbo.TIMOVIMIENTOENCAB.MV_TIPO AND
		dbo.TMMOVIMIENTOFACTURACIONE.MV1_NUM = dbo.TIMOVIMIENTOENCAB.MV_NUM 
	LEFT JOIN dbo.TKCLIENTES
		ON dbo.TKCLIENTES.KC_ZONA = dbo.TIMOVIMIENTOENCAB.MV_ZONA AND 
		dbo.TKCLIENTES.KC_COD = dbo.TIMOVIMIENTOENCAB.MV_COD AND 
		dbo.TKCLIENTES.KC_SEQK = dbo.TIMOVIMIENTOENCAB.MV_SEQK 
	LEFT JOIN dbo.TMUSUARIOSFACTURACION
		ON dbo.TMUSUARIOSFACTURACION.KC2_ZONA = dbo.TIMOVIMIENTOENCAB.MV_ZONA AND 
		dbo.TMUSUARIOSFACTURACION.KC2_COD = dbo.TIMOVIMIENTOENCAB.MV_COD AND 
		dbo.TMUSUARIOSFACTURACION.KC2_SEQK = dbo.TIMOVIMIENTOENCAB.MV_SEQK 
	LEFT JOIN dbo.TMENTIDADES ON dbo.TMMOVIMIENTOFACTURACIONE.MV1_ENTIDAD = dbo.TMENTIDADES.ENT_COD 
	LEFT JOIN TITIPOSDOCUMENTOS ON (TITIPOSDOCUMENTOS.TA_TIPO_DOC = TIMOVIMIENTOENCAB.MV_TIPO)
	LEFT JOIN dbo.TIARTICULOS ON dbo.TIARTICULOS.MI_ARTIC = dbo.TIMOVIMIENTODETALLE.MV2_ARTIC 
	WHERE TIMOVIMIENTOENCAB.MV_ANULADO IS NULL
	AND TIMOVIMIENTOENCAB.MV_TIPO IN ('V01','V02','V03','V04','V05','V06','V07','V08','V09','V10','V11','V12','V13','V14','V20','V21','V22','V23','V24','V25','V26','V27')
	AND TIMOVIMIENTODETALLE.MV2_ARTIC IN
	(
		'*892901-10',
		'*950601-12',
		'*993102',   
		'*993102-4', 
		'*993104-1', 
		'*993106-1', 
		'*993120',   
		'*993120-8', 
		'*993122',   
		'*993130-1', 
		'*993501',   
		'*993502-1', 
		'*993503-1', 
		'*993503-4', 
		'*993504-1', 
		'*993505',   
		'*993506-1', 
		'*993509-1', 
		'*993510-1', 
		'*993512-1', 
		'*993513',   
		'*993520',   
		'*993522',   
		'*993522-1', 
		'*995201',   
		'*697100',
		'*861801'
	)
	AND TIMOVIMIENTOENCAB.MV_FCH > 20121231
	AND TKCLIENTES.KC_FCH_NACE IS NOT NULL
	AND TMENTIDADES.ENT_COD_SUPER IS NOT NULL
	AND dbo.TIMOVIMIENTOENCAB.MV_ZONA = '99'
