SELECT [Id]
      ,[Departamento]
      ,[Municipio]
      ,[FechaAtencion]
      ,[AñoAtencion]
      ,[MesAtencion]
      ,[NombreMes]
      ,[Sexo]
      ,[FechaNacimiento]
      ,[Edad]
      ,[UnidadEdad]
      ,[CodigoSupersalud]
      ,[NombreEntidad]
      ,[Regimen]
      ,[CodigoCups]
      ,[DescripcionCodigoCups]
      ,[ConceptoProduccion]
      ,[EsExtranjero]
      ,[Zona]
  FROM [DatosAbiertos].[dbo].[Consultas]
  WHERE ConceptoProduccion IN 
	(
	'CONSULTA DE SEGUIMIENTO REVISION',
	'CONSULTA DE CONTROL MEDICO HTA PARA EPS',
	'CONSULTA DE PRIMERA VEZ HTA- MEDICO',
	'CONSULTA DE CONTROL MEDICO DE HTA',
	'PYP CONSULTA DE CONTROL POR MEDICO POSTPARTO',
	'PYP CONSULTA DE CONTROL POR MEDICO RECIEN NACIDO',
	'PYP CONSULTA PRIMERA VEZ PLANIFICACION FAMILIAR MEDICO',
	'PYP CONSULTA PRIMERA VEZ PLANIFICACION FAMILIAR ENFERMERA',
	'PYP CONSULTA CONTROL PLANIFICACION FAMLIAR MEDICO',
	'PYP CONSULTA CONTROL PLANIFICACION FAMILIAR ENFERMERA',
	'PYP CONSULTA PRIMERA VEZ CYD MEDICO',
	'PYP CONSULTA CONTROL CYD MEDICO',
	'PYP CONSULTA CONTROL CYD ENFERMERA',
	'PYP CONSULTA PRIMERA VEZ JOVEN MEDICO',
	'CONSULTA DE CONTROL POR ENFERMERIA HTA',
	'PYP CONSULTA PRIMERA VEZ PRENATAL MEDICO',
	'PYP CONSULTA POR ODONTOLOGIA GENERAL - MATERNA',
	'PYP CONSULTA DE PRIMERA VEZ CONTROL PRENATAL ENFERMERIA',
	'PYP CONSULTA CONTROL PRENATAL MEDICO',
	'PYP CONSULTA DE CONTROL ENFERMERIA GESTANTES',
	'PYP CONSULTA PRIMERA VEZ ADULTO MEDICO'
	)