/*
	Obtener Signos Vitales
	Segun Número de Documento, Fecha Inicial y Fecha Final
*/

USE
BETANIA
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FUC_SV_01]')
AND TYPE IN (N'FN', N'IF',N'TF', N'FS', N'FT'))
DROP FUNCTION dbo.FUC_SV_01
GO
CREATE FUNCTION dbo.FUC_SV_01 (@Codigo AS VARCHAR(20), @FechaInicial AS VARCHAR(8), @FechaFinal AS VARCHAR(8))
RETURNS TABLE
AS
RETURN
(
	SELECT
		 TQMOVIMIENTOHC.QM1_COD Codigo

		-- Signos Vitales

		,CONVERT(INT,TQMOVIMIENTOHC.QM1_NUM_PESO) Peso
		,TQMOVIMIENTOHC.QM1_COD_UNIPESO UnidadPeso
		,CASE
			WHEN TQMOVIMIENTOHC.QM1_COD_UNIPESO = 'G' THEN CONVERT(INT,TQMOVIMIENTOHC.QM1_NUM_PESO) / 1000
			ELSE CONVERT(INT,TQMOVIMIENTOHC.QM1_NUM_PESO)
		END PesoKg
		,TQMOVIMIENTOHC.QM1_TALLA_CM AS Talla	

		,TQMOVIMIENTOHC.QM1_EST_ARTE_S PresionSistolica
		,TQMOVIMIENTOHC.QM1_EST_ARTE_D PresionDiastolica

		-- Diagnóstico - Otros Datos del Diagnóstico
		,TQMOVIMIENTOHC.QM1_COD_DX2PP DiagnosticoPrincipal
		,TQMOVIMIENTOHC.QM1_COD_DX2R1 DiagnosticoRelacionado1
		,TQMOVIMIENTOHC.QM1_COD_DX2R2 DiagnosticoRelacionado2
		,TQMOVIMIENTOHC.QM1_COD_DX2R3 DiagnosticoRelacionado3
		,TQMOVIMIENTOHC.QM1_TIPO_DIAG TipoDiagnostico
		,TQMOVIMIENTOHC.QM1_TIPO_DISCAP TipoDiscapacidad
		,TQMOVIMIENTOHC.QM1_GRADO_DISCAP GradoDiscapacidad

		-- Diagnóstico - Finalidad/Causa
		,TQMOVIMIENTOHC.QM1_EST_FINACON Finalidad
		,TQMOVIMIENTOHC.QM1_EST_CAUSAEXT CausaExterna
		,TQMOVIMIENTOHC.QM1_EST_SINTRESP SintomaticoRespiratorio

		,[QM1_EDAD_DIAS] EdadDias
		,[QM1_EDAD_MESES] EdadMeses
		,CONVERT(INT,[QM1_EDAD_ANOS],0) Edad

		,CONVERT(VARCHAR,CAST(CAST(TQMOVIMIENTOHC.QM1_FCH_FECHA AS VARCHAR) AS DATE),23) FechaAtencion
		,TMMEDICOS.MED_NOMBRE Responsable
		
		,TQMOVIMIENTOHC.QM1_COD_TIPOATEN TipoAtencion
		,TQCONFIGURARHC.QP1_NOM NombreAtencion
		,TQMOVIMIENTOHC.QM1_NUM_CONSE Consecutivo

	FROM 
		TQMOVIMIENTOHC

	LEFT JOIN TMMEDICOS
	ON TQMOVIMIENTOHC.QM1_NUM_MED = TMMEDICOS.MED_COD

	LEFT JOIN TQCONFIGURARHC 
	ON TQCONFIGURARHC.QP1_COD_ESP = TQMOVIMIENTOHC.QM1_COD_ESP AND TQCONFIGURARHC.QP1_COD_TIPOATEN = TQMOVIMIENTOHC.QM1_COD_TIPOATEN

	WHERE
	CONVERT(BIGINT,TQMOVIMIENTOHC.QM1_COD) = @Codigo
	AND TQMOVIMIENTOHC.QM1_FCH_FECHA BETWEEN @FechaInicial AND @FechaFinal
	AND TQMOVIMIENTOHC.QM1_NUM_PESO IS NOT NULL
	AND TQMOVIMIENTOHC.QM1_FCH_FECHA <> 0
	AND TQMOVIMIENTOHC.QM1_EST_ANULADO IS NULL
	AND TQMOVIMIENTOHC.QM1_COD_TIPOATEN NOT IN ('X01M','X03','X04','X05','X07','X05P','X05U','X23A','X24','X24O','X27A','X30A','X31A','X31N','X32A','X33A','X33P','X35','X36','X41D','X41E','X41T')
);
GO
SELECT TOP 1 Peso, UnidadPeso, PesoKg, Talla, EdadDias, EdadMeses, Edad, FechaAtencion, Responsable, TipoAtencion, NombreAtencion, Consecutivo FROM dbo.FUC_SV_01('3377436',20221201, 20221131) ORDER BY FechaAtencion DESC

--SELECT * FROM TQMOVIMIENTOHC WHERE QM1_COD LIKE '%3369230%' AND QM1_NUM_CONSE = 22 ORDER BY QM1_FCH_FECHA DESC