/*
	Obtener Agendas Según Fecha y Código Médico
*/
USE
BETANIA
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FUC_AG_01]')
AND TYPE IN (N'FN', N'IF',N'TF', N'FS', N'FT'))
DROP FUNCTION dbo.FUC_AG_01
GO
CREATE FUNCTION dbo.FUC_AG_01 (@Codigo AS DECIMAL(8,0), @Fecha AS DECIMAL(12,0))
RETURNS TABLE
AS
RETURN
(
	SELECT
		 TMTURNOSMEDICOSDETALLE.TME2_SEQ Consecutivo
		,DBO.FUX_FORMATO_FECHA_XLS(TMTURNOSMEDICOS.TME_FCH) Fecha
		,RIGHT( '00' + CAST(TMTURNOSMEDICOSDETALLE.TME2_HH AS VARCHAR(2)), 2 )+':'+RIGHT( '00' + CAST(TMTURNOSMEDICOSDETALLE.TME2_MM AS VARCHAR(2)), 2 ) Hora
		,ISNULL(CAST(TMTURNOSMEDICOSDETALLE.TME2_COD AS FLOAT),'') CodigoUsuario
		,ISNULL(TKCLIENTES.KC_NOM,'') NombreUsuario
		,ISNULL(TKCLIENTES.KC_TEL1,'') +' - '+ ISNULL(TMUSUARIOSFACTURACION.KC2_TEL_RESP,'') +' - '+ ISNULL(TKCLIENTES.KC_TEL2,'') +' - '+ ISNULL(TMUSUARIOSFACTURACION.KC2_TEL_ACOMP,'') Telefonos
		,ISNULL(TMTURNOSMEDICOS.TME_CODM,'') CodigoProfesional
		,ISNULL(TMMEDICOS.MED_NOMBRE,'') Profesional
		,ISNULL(TIARTICULOS.MI_ARTIC,'') CodigoActividad
		,ISNULL(TIARTICULOS.MI_DESC,'') Actividad

	FROM TMTURNOSMEDICOS
	 LEFT JOIN TMTURNOSMEDICOSDETALLE ON TMTURNOSMEDICOS.TME_CODM = TMTURNOSMEDICOSDETALLE.TME2_CODM AND TMTURNOSMEDICOS.TME_FCH = TMTURNOSMEDICOSDETALLE.TME2_FCH
	 LEFT JOIN TKCLIENTES ON ISNULL(TMTURNOSMEDICOSDETALLE.TME2_ZONA,' ') = KC_ZONA and isnull(TME2_COD,' ') = KC_COD and isnull(TME2_SEQK,' ') = KC_SEQk
	 LEFT JOIN TMCITASUSUARIOS  ON isnull(TME2_CODM,0) = KC3_MEDICO and  isnull(TME2_ZONA,' ') = KC3_ZONA and isnull(TME2_COD,' ') = KC3_COD and isnull(TME2_SEQK,' ') = KC3_SEQk
			   AND TME2_FCH = KC3_FCH  and TME2_HH = KC3_HH   and  TME2_MM = KC3_MM
	 LEFT JOIN TMMEDICOS ON TME2_CODM = TMMEDICOS.MED_COD
	 LEFT JOIN TMUSUARIOSFACTURACION ON isnull(TME2_ZONA,' ') = KC2_ZONA and isnull(TME2_COD,' ') = KC2_COD and isnull(TME2_SEQK,' ') = KC2_SEQk
	 LEFT JOIN TIARTICULOS ON isnull(kc3_Artic,' ') = MI_ARTIC
	 WHERE  KC3_ESTADO IS NULL
	 AND TMTURNOSMEDICOS.TME_CODM = @Codigo
	 AND TMTURNOSMEDICOSDETALLE.TME2_FCH = @Fecha
 )
 GO
 SELECT * FROM dbo.FUC_AG_01(4546849,20230519) ORDER BY Consecutivo