/*
	Obtiene
		Resultado Examen de Laboratorio
	
	Parámetros
		Número de Documento
		Fecha Inicial
		Fecha Final
		Código CUPS
		Código Parametro
*/
USE
BETANIA
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[F_RESULTADO_LABORATORIO]')
AND type in (N'FN', N'IF',N'TF', N'FS', N'FT'))
DROP FUNCTION dbo.F_RESULTADO_LABORATORIO
GO
CREATE FUNCTION dbo.F_RESULTADO_LABORATORIO (@Codigo AS VARCHAR(20),@FechaInicial VARCHAR(8), @FechaFinal VARCHAR(8), @CUPS VARCHAR(7), @Parametro VARCHAR(3))
RETURNS TABLE
AS
RETURN
	(
	SELECT
		 TMRESULTADOSLABORATORIOD.RL2_OBS Resultado
		,CONVERT(VARCHAR,CAST(CAST(TMRESULTADOSLABORATORIOD.RL2_FCH AS VARCHAR) AS DATE),23) AS Fecha
	FROM
	TMRESULTADOSLABORATORIOD

	WHERE 
	CONVERT(BIGINT,TMRESULTADOSLABORATORIOD.RL2_COD_COD) = @Codigo
	AND TMRESULTADOSLABORATORIOD.RL2_COD_ARTIC IN (@CUPS)
	AND TMRESULTADOSLABORATORIOD.RL2_COD_PARA IN (@Parametro)
	AND TMRESULTADOSLABORATORIOD.RL2_FCH BETWEEN @FechaInicial AND @FechaFinal
	AND TMRESULTADOSLABORATORIOD.RL2_OBS IS NOT NULL
);
GO
SELECT TOP 1 Resultado, Fecha FROM dbo.F_RESULTADO_LABORATORIO('568236','20230101','20230630','*903841','074') ORDER BY Fecha DESC