-- SELECCIONAR PRESION SISTOLICA Y DIASTOLICA

SELECT [QM1_EST_ARTE_S] , [QM1_EST_ARTE_D], QM1_NUM_CONSE FROM TQMOVIMIENTOHC
WHERE CONVERT(BIGINT,QM1_COD) = 21460420
--AND QM1_OEST_TALLA = '126'
ORDER BY QM1_NUM_CONSE DESC

-- ACTUALIZAR PRESION SISTOLICA Y DIASTOLICA

UPDATE TQMOVIMIENTOHC
SET [QM1_EST_ARTE_S] = '120', [QM1_EST_ARTE_D] = '80'
WHERE CONVERT(BIGINT,QM1_COD) = 21460420
--AND QM1_OEST_TALLA = '124'