SELECT [Id]
      ,[Departamento]
      ,[Municipio]
      ,[FechaAtencion]
      ,[AñoAtencion]
      ,[MesAtencion]
      ,[NombreMes]
      ,[Sexo]
      ,[FechaNacimiento]
      ,[Edad]
      ,[UnidadEdad]
      ,[CodigoSupersalud]
      ,[NombreEntidad]
      ,[Regimen]
      ,[CodigoCups]
      ,[DescripcionCodigoCups]
      ,[ConceptoProduccion]
      ,[EsExtranjero]
      ,[Zona]
	  ,Cantidad
  FROM [DatosAbiertos].[dbo].HigieneOral
