USE [master]
ALTER DATABASE [BETANIA] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [BETANIA] 
FROM  DISK = N'D:\BackUp_Db2\BETANIA_backup_2023_02_27_190002_6702408.bak' 
WITH  FILE = 1,  
MOVE N'betania' TO N'D:\DatosSQL\BETANIA.mdf',  
MOVE N'betania_log' TO N'D:\DatosSQL\BETANIA_log.ldf',
NOUNLOAD,  
REPLACE,
STATS = 5
ALTER DATABASE [BETANIA] SET MULTI_USER
GO


