USE [master]
ALTER DATABASE NIFF SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE NIFF 
FROM  DISK = N'D:\BackUp_Db2\BETANIA_backup_2023_03_21_190004_8200382.bak' 
WITH  FILE = 1,  
MOVE N'betania' TO N'D:\Datos_SQL\NIFF.mdf',  
MOVE N'betania_log' TO N'D:\Datos_SQL\NIFF_log.ldf',
NOUNLOAD,  
REPLACE,
STATS = 5
ALTER DATABASE NIFF SET MULTI_USER 
GO